In [ ]:
# Hamiltonian Eigenvalues

In [39]:
# Import libraries
import numpy as np
from matplotlib import pyplot as plt
from scipy.stats import norm

$V(x) = -V_0 e^{-\alpha x^2}$

In [59]:
# declarations
n = 5
L = 5
V_0 = -5
alpha = 1
x = np.linspace(-L, L, n)
dx = (2*L)/n
V = np.zeros(n)
h = np.zeros((n, n))

# functions
def potential(x):
    return -V_0*(np.e**(-alpha*(x**2)))

# plot potential
for i in range(0, n):
    V[i] = potential(x[i])

In [60]:
# generate matrix
for i in range(0, n):
    h[i][i] = (1/(2*(dx**2)))+V[i]
    if i != n-1:
        h[i][i+1] = -1/(dx**2)
    if i != 0:
        h[i][i-1] = -1/(dx**2)

# find eigenvalues and eigenvectors
h_eig = np.linalg.eig(h)

# display some results
print("First 5 Eigenvalues:")
for i in range(0, 5):
    print(h_eig[0][i])
    
print("First 5 Eigenvectors:")
for i in range(0, 5):
    print(h_eig[1][i])

print("First 5 Probability Densities:")
for i in range(0, 5):
    print(norm.cdf(h_eig[0][i]))

First 5 Eigenvalues:
5.149985531309217
0.3798727142000958
0.36682888272904307
-0.1321621432876854
-0.12022044344951774
First 5 Eigenvectors:
[-0.00247993  0.49515125  0.50755988  0.4923178  -0.50480218]
[ 0.04984644 -0.50480218 -0.49097055  0.50642201 -0.49515125]
[-9.97506073e-01 -5.10589496e-16 -5.15923599e-02  4.81649598e-02
 -4.36855410e-17]
[ 0.04984644  0.50480218 -0.49097055  0.50642201  0.49515125]
[-0.00247993 -0.49515125  0.50755988  0.4923178   0.50480218]
First 5 Probability Densities:
0.9999998697467227
0.6479800486633204
0.6431266690284673
0.4474280218430898
0.45215426184679813
